name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.0
      - name: Install backend dependencies
        run: |
          cd backend
          npm install
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      - name: Deploy to DigitalOcean Droplet
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          sshpass -p "${SSH_KEY}" ssh -o StrictHostKeyChecking=no ${SSH_USERNAME}@${SSH_HOST} << 'EOF'
          cd ~/MERN
          git pull origin main
          
          # Build frontend
          cd frontend
          npm install
          npm run build
          sudo cp -r dist/* /var/www/html/
          
          # Update backend
          cd ../backend
          npm install
          
          # Restart services
          pm2 restart mern-backend
          sudo systemctl restart nginx
          
          EOF
